version: "3.8"
#########
# USAGE #
#########
# > $env:DOCKER_HOST="ssh://$PiUser@$PiIp"
# > docker secret create pihole_password ...
# > docker stack deploy --compose-file pihole.yml PIHOLE

secrets:
  pihole_password:
    external: true
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:

  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    dns: 127.0.0.1
    environment:
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      IPv6: 'false'
      TZ: 'CEST-2'
      DNSMASQ_LISTENING: 'all'
      DNS1: '192.168.1.22#5053'
      DNS2: ''
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    secrets:
      - pihole_password
    deploy:
      mode: global
      endpoint_mode: vip
      labels: [APP=PIHOLE]
      restart_policy:
        condition: on-failure
        delay: 6s
        window: 120s

  cloudflared:
    image: visibilityspots/cloudflared:latest
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
    environment:
      PORT: 5053
    deploy:
      mode: global
      endpoint_mode: vip
      labels: [APP=PIHOLE]
      restart_policy:
        condition: on-failure
        delay: 6s
        window: 120s